version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
        - sms
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
        - sms
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    image: redis/redis-stack-server
    container_name: redis
    ports:
      - "6379:6379"
    networks:
        - sms
  scylla:
    image: scylladb/scylla
    container_name: scylla
    ports:
      - "22:22"
      - "6999:7000"
      - "7001:7001"
      - "9042:9042"
      - "9160:9160"
      - "9180:9180"
      - "10000:10000"
    networks:
        - sms

networks:
    sms:
        driver: bridge
